# Generated by Django 4.1.dev20211004082034 on 2021-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
