# Generated by Django 4.1.dev20211004082034 on 2021-10-26 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='variant',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.image'),
        ),
    ]
