# Generated by Django 4.1.dev20211004082034 on 2021-10-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='product',
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(related_name='collections', through='store.ProductCollection', to='store.Product'),
        ),
    ]
