# Generated by Django 4.1.dev20211004082034 on 2021-10-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_category_alter_variant_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='subcategories',
        ),
    ]
