# Generated by Django 4.1.dev20211004082034 on 2021-11-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.FileField(upload_to='image/'),
        ),
    ]
