# Generated by Django 4.1.dev20211004082034 on 2021-11-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(upload_to='product_pics/'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description', 'created_at', 'updated_at'], name='store_produ_descrip_e3408e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='title_index'),
        ),
    ]
