# Generated by Django 3.2.9 on 2021-11-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_category_parent_alter_image_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.image'),
        ),
    ]
